#!/usr/bin/env bash
#
# Usage: chksub <qsub_jobid>
#
# Description: real-time check of orca submission output
#
##

usage() {
	echo "Usage: chksub <qsub_jobid>"
}

## check arguments
if [[ $# -lt 1 ]]
then
	echo "Argument required"
	usage
	exit 1
elif [[ $# -gt 1 ]]
then
	echo "Too many arguments"
	usage
	exit 1
fi

JOB_ID=$1

INPUT=$(qstat -j $JOB_ID | grep job_name | cut -d: -f2 | tr -d ' ')
FILE=${INPUT%.inp}
NODE=$(qstat -u "*" | grep $JOB_ID | grep -ow node..)
OUTPUT=${FILE}.out
OWNER=$(qstat -j $JOB_ID | grep owner | cut -d: -f2 | tr -d ' ')
SCRATCH='/scratch'
WORKING_DIR=$(qstat -j $JOB_ID | grep cwd | cut -d: -f2 | tr -d ' ')

echo $OUTPUT

## check output file
ssh $NODE tail -f ${SCRATCH}/${OWNER}/${JOB_ID}/$OUTPUT
