#!/usr/bin/env bash
#
# name: wrap-gaussian09
# usage: qsub -pe openmp <SLOTS> -N <INPUT_FILE> <WRAPPER>
# description: wrapper script for sge job submission using 
#              local scratch storage
#
#   1. Specify BINARY (e.g. matlab, g16, python)
#       Example(R):
#           BINARY=Rscript
#
#   2. Use NSLOTS placeholder rather than explicitly specifying
#      the number of slots.
#       Example(orca): 
#           %pal nprocs NSLOTS
#           end
#       Example(gaussian): 
#           %NProcShared=NSLOTS
#
#   3. Use AUX_INPUT/AUX_OUTPUT to add additional input/output
#      files with the indicated file extension.
#       Example(matlab):
#           AUX_OUTPUT=(mat mex)
#
# author: tonyvo
# date: 2017-06-13
#
#$ -q admin.q
#$ -cwd
#$ -S /bin/bash
#$ -e error.log
#$ -o job.log
# -m bea
# -M <email>
# -l h_rt=<hh>:<mm>:

INPUT=$JOB_NAME
FILE="${INPUT%.*}"
EXTENSION="${INPUT#${FILE}.}"
SCRATCH=/scratch
SCRATCH_DIR="${SCRATCH}/${USER}/${JOB_ID}"
WORKING_DIR=$PWD

########## BEGIN USER CUSTOMIZATION ##########
 
AUX_INPUT=()                                      
AUX_OUTPUT=() 
BINARY=g09
MODULES=(gaussian/09)
OUTPUT="${FILE}.log"
PROGRAM_OPTIONS=""

########### END USER CUSTOMIZATION ###########

#/*
#  
#  FUNCTIONS
#
###*/

create_job_header() {
    ## create file with job metadata
    date +'%a %d %B %Y %H:%M:%S'
    echo "$JOB_ID $(hostname)"
    echo $WORKING_DIR
}

create_scratch() {
    ## create user scratch directory and populate with program files
    ([[ -d $SCRATCH_DIR} ]] || mkdir -p $SCRATCH_DIR) &&
    cp -f $INPUT $SCRATCH_DIR &&
    (
        sed -i "s/NSLOTS/${NSLOTS}/" "${SCRATCH_DIR}/${INPUT}";
        for EXTENSION in "${AUX_INPUT[@]}"; do
            cp *.${EXTENSION} $SCRATCH_DIR 2> /dev/null
        done
    )
}

load_module() {
    ## load required modules for computation
    source /etc/profile.d/modules.sh &&
    module load "${MODULES[@]}"
    PROGRAM=$(which $BINARY)
}

run_program() {
    ## run program to perform computation on data
    cd $SCRATCH_DIR
    $PROGRAM $PROGRAM_OPTIONS $INPUT > $OUTPUT
}

save_output() {
    ## copy results from scratch to working directory
    cp $OUTPUT $WORKING_DIR
    for EXTENSION in "${AUX_OUTPUT[@]}"; do
        cp *.${EXTENSION} $WORKING_DIR 2> /dev/null
    done

    ## clean up intermediate files
    rm -rf $SCRATCH_DIR
}

#/*
#
#  MAIN
#
###*/

load_module
create_job_header
create_scratch
run_program
save_output
